"""Initial schema — create all Stocky tables.

Baseline migration: builds the full schema from the SQLModel metadata so it always matches
the models exactly. Subsequent schema changes should use normal autogenerated migrations
(`make migrate-create m="..."`).

Revision ID: 0001
Revises:
Create Date: 2026-06-27
"""

from __future__ import annotations

from collections.abc import Sequence

from sqlmodel import SQLModel

# Import models so their tables register on the metadata.
import app.models  # noqa: F401
from alembic import op

revision: str = "0001"
down_revision: str | None = None
branch_labels: str | Sequence[str] | None = None
depends_on: str | Sequence[str] | None = None


def upgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.create_all(bind)


def downgrade() -> None:
    bind = op.get_bind()
    SQLModel.metadata.drop_all(bind)
